const dataProduksi = [
    {
        "Mesin": "TW002",
        "Speed Interfold": 600,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW404",
        "Speed Interfold": 869,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW405",
        "Speed Interfold": 869,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "JT005",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 23000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "FC121",
        "Speed Interfold": 1000,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": 63,
        "Satuan.2": "Cut/Min",
        "Speed Packaging": 60,
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW406",
        "Speed Interfold": 800,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW407",
        "Speed Interfold": 800,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP313",
        "Speed Interfold": 650,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "FC122",
        "Speed Interfold": 1000,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": 100,
        "Satuan.2": "Cut/Min",
        "Speed Packaging": 65,
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "JT006",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 28000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TL204",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 25000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP314",
        "Speed Interfold": 952,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP315",
        "Speed Interfold": 952,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW408",
        "Speed Interfold": 976,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW409",
        "Speed Interfold": 976,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "HRT001",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 25000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "HRT002",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 25000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP002",
        "Speed Interfold": 600,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP007",
        "Speed Interfold": 800,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP317",
        "Speed Interfold": 900,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP318",
        "Speed Interfold": 900,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP319",
        "Speed Interfold": 882,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP321QLT",
        "Speed Interfold": 400,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP321",
        "Speed Interfold": 750,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP320",
        "Speed Interfold": 697,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW410",
        "Speed Interfold": 800,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP316",
        "Speed Interfold": 857,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW411",
        "Speed Interfold": 652,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "FC118",
        "Speed Interfold": 1000,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "",
        "Speed Logsaw": 200,
        "Satuan.2": "Cut/Min",
        "Speed Packaging": 140,
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "HRT003",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 90,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW412",
        "Speed Interfold": 625,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "TW413",
        "Speed Interfold": 300,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "Cm/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP322",
        "Speed Interfold": 800,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "NP324",
        "Speed Interfold": 900,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "FC108",
        "Speed Interfold": 1000,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": 100,
        "Satuan.2": "Cut/Min",
        "Speed Packaging": 65,
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "FC103",
        "Speed Interfold": 1000,
        "Satuan": "Sheet/Min",
        "Speed Roll": 0,
        "Satuan.1": "M/Min",
        "Speed Logsaw": 100,
        "Satuan.2": "Cut/Min",
        "Speed Packaging": 65,
        "Satuan.3": "Pack/Min"
    },
    {
        "Mesin": "HRT004",
        "Speed Interfold": 0,
        "Satuan": "Sheet/Min",
        "Speed Roll": 25000,
        "Satuan.1": "M/Min",
        "Speed Logsaw": "",
        "Satuan.2": "Cut/Min",
        "Speed Packaging": "",
        "Satuan.3": "Pack/Min"
    }
];
export default dataProduksi;
